### PR TITLE
typo in code block in README

### PR DESCRIPTION
**Pull request by dar-tau**
fixing code block typo in readme

### CODE REVIEW

**Comment by dar-tau** [comment]
@googlebot I signed it!

**Comment by dar-tau** [comment]
@googlebot I fixed it.

**Comment by dar-tau** [comment]
@googlebot I fixed it.

**Comment by guyd1995** [comment]
@googlebot I consent.

**Comment by MostafaDehghani** [comment]
Thank you @dar-tau.

**Pull request merged**
